version: '3.8'

services:
  quarkapi:
    build: .
    container_name: quarkapi
    ports:
      - "7024:3000"
    environment:
      - QUARK_COOKIE=
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
